### ISSUE TITLE
fails silently on images with dimensions not 2^n

### ISSUE THREAD

**Issue by Fusselwurm** [gruppe-adler/paa-gimp-plugin#2]
imo there should be a hint why its not working

**Comment by TheWillard** [comment]
Depending on your settings there should be either a dialog box or a message in your error console:

![](https://i.imgur.com/6SU7Uvb.png)

I need to check if I can force a dialog box since the error console is very hidden (ref: https://developer.gimp.org/api/2.0/libgimp/libgimp-gimpmessage.html).

**Comment by TheWillard** [comment]
Fixed by using `gimp_message_set_handler(GimpMessageHandlerType::GIMP_MESSAGE_BOX)` in combination with a message which consists of more than one line.

**Comment by Fusselwurm** [comment]
wenn ich diesen Menüpunkt nutze, krieg ich eine Modalbox mit Fehlermeldung:  👍 

![Unbenannt](https://user-images.githubusercontent.com/52833/85949838-4fc8a980-b959-11ea-9905-d034f72a1c66.png)

*Aber* wenn ich das "Exportieren nach"-Menü nutze gibts keine Modalbox, auch keine Meldung in der Fehlerkonsole, stattdessen in der Statusleiste gelogenes Erfolgs-Hurra: 👎 

![Unbenannt](https://user-images.githubusercontent.com/52833/85949890-a2a26100-b959-11ea-959f-a135882e7f61.png)

**Comment by TheWillard** [comment]
Should be fixed with d0c47f5c59252a2099cdc9c949058dc5853ed9f1
