### ISSUE TITLE
creates foo when exporting (or importing?) non-square images

### ISSUE THREAD

**Issue by Fusselwurm** [gruppe-adler/paa-gimp-plugin#3]
I know PAAs with dimensions like 1024x512 do exist (one of these is the logo of project opfor), but when I try to export with these dimensions 

![nooo](https://user-images.githubusercontent.com/52833/85928985-69aeb180-b8b1-11ea-8c63-7f6c50f3d4ea.png)

and re-open again I get this: 

![nooo](https://user-images.githubusercontent.com/52833/85928964-526fc400-b8b1-11ea-98e2-d2febc302550.png)

**Comment by TheWillard** [comment]
Should be fixed in https://github.com/gruppe-adler/grad_aff/commit/9a2a3fecfd2bb64c3e7b07b869d4c28898238d95#diff-021285601456776869ddb98f5ed73fe4R145
