### ISSUE TITLE
Getting issue when openeing Gimp

### ISSUE THREAD

**Issue by Salbei2500** [gruppe-adler/paa-gimp-plugin#4]
https://i.imgur.com/c50tJXq.png

Getting this issue when opening Gimp

**Comment by TheWillard** [comment]
What's your Gimp Version?

**Comment by Salbei2500** [comment]
2.10.12

Ziehe mir mal ebend die neuste Version, nerfig das es sich nicht selbst updaten kann :(

**Comment by Salbei2500** [comment]
Ja, falsche version.

**Comment by Sherakis** [comment]
I get the same error in GIMP 2.10.28

**Comment by TheWillard** [comment]
Thanks for reporting this error, i did a rebuild for GIMP 2.10.28 and it should be fixed in the newest release (0.3.1).
